// 中文內文人名與作品名的英文對照（畫家與本站作品會自動加入，這裏只列其他名稱）。
// 作品名連同書名號《》或〈〉一併作為鍵。
// 值為 null 表示「這個詞組不要加註」：用來擋住較短名稱的誤配，例如「奧斯曼帝國」不是奧斯曼男爵。
// 只收人名與作品名（包括書籍、電影、樂曲）；聖經及神話人物、地名與機構不加註。
export const EXTRA_NAMES: Record<string, string | null> = {
  // ── 畫家的簡稱或別稱 ──
  "布勒哲爾": "Pieter Bruegel the Elder",
  "荷爾拜因": "Hans Holbein the Younger",
  "阿特米謝": "Artemisia Gentileschi",
  "羅特列克": "Henri de Toulouse-Lautrec",
  "科爾": "Thomas Cole",
  "米開朗基羅·梅里西": "Michelangelo Merisi da Caravaggio",

  // ── 不應加註的詞組 ──
  "拉斐爾前派": "Pre-Raphaelites",
  "拉斐爾房間": "Raphael Rooms",
  "卡拉瓦喬派": "Caravaggisti",
  "卡拉瓦喬式照明": null,
  "拿破崙戰爭": "Napoleonic Wars",
  "拿破崙帝國": null,
  "奧斯曼帝國": null,
  "波希米亞": null,
  "莫斯科": null,
  "路德派": null,
  "路德宗": null,
  "梵高博物館": null,
  "梵高咖啡館": null,
  "孟克博物館": null,
  "畢加索博物館": null,
  "莫內夫人": null,
  "王后瑪麗安娜": "Mariana of Austria",
  "「瑪麗安娜」": "Marianne",
  "愛女艾琳": "Aline Gauguin",

  // ── 人物 ──
  "喬凡尼·阿爾諾芬尼": "Giovanni di Nicolao Arnolfini",
  "科斯坦薩·特倫塔": "Costanza Trenta",
  "潘諾夫斯基": "Erwin Panofsky",
  "羅塞蒂": "Dante Gabriel Rossetti",
  "亨特": "William Holman Hunt",
  "拿破崙三世": "Napoleon III",
  "拿破崙": "Napoleon Bonaparte",
  "洛倫佐·迪皮耶爾弗朗切斯科·德美第奇": "Lorenzo di Pierfrancesco de' Medici",
  "美第奇家族": "the Medici",
  "奧維德": "Ovid",
  "盧克萊修": "Lucretius",
  "瓦薩里": "Giorgio Vasari",
  "菲奇諾": "Marsilio Ficino",
  "柏拉圖": "Plato",
  "薩伏那洛拉": "Girolamo Savonarola",
  "西蒙內塔·韋斯普奇": "Simonetta Vespucci",
  "提香": "Titian",
  "魯本斯": "Peter Paul Rubens",
  "安迪·沃荷": "Andy Warhol",
  "沃荷": "Andy Warhol",
  "盧多維科·斯福爾扎": "Ludovico Sforza",
  "腓力二世": "Philip II of Spain",
  "達利": "Salvador Dalí",
  "麗莎·蓋拉爾迪尼": "Lisa Gherardini",
  "弗朗切斯科·德爾焦孔多": "Francesco del Giocondo",
  "法蘭索瓦一世": "Francis I of France",
  "佩魯賈": "Vincenzo Peruggia",
  "科特": "Pascal Cotte",
  "畢加索": "Pablo Picasso",
  "阿波利奈爾": "Guillaume Apollinaire",
  "杜尚": "Marcel Duchamp",
  "儒略二世": "Pope Julius II",
  "布拉曼特": "Donato Bramante",
  "赫拉克利特": "Heraclitus",
  "第歐根尼": "Diogenes",
  "亞里士多德": "Aristotle",
  "歐幾里得": "Euclid",
  "希帕提婭": "Hypatia",
  "讓·德丹特維爾": "Jean de Dinteville",
  "德丹特維爾": "Jean de Dinteville",
  "喬治·德塞爾夫": "Georges de Selve",
  "德塞爾夫": "Georges de Selve",
  "亨利八世": "Henry VIII",
  "安妮·博林": "Anne Boleyn",
  "馬丁·路德": "Martin Luther",
  "尼克拉斯·容赫林克": "Niclaes Jongelinck",
  "聖休伯特": "Saint Hubert",
  "聖尤斯塔斯": "Saint Eustace",
  "塔可夫斯基": "Andrei Tarkovsky",
  "威廉斯": "William Carlos Williams",
  "約翰·貝里曼": "John Berryman",
  "肯塔雷利": "Matteo Contarelli",
  "科西莫二世": "Cosimo II de' Medici",
  "塔西": "Agostino Tassi",
  "伽利略": "Galileo Galilei",
  "多納泰羅": "Donatello",
  "班寧·柯克": "Frans Banninck Cocq",
  "羅伊滕伯赫": "Willem van Ruytenburch",
  "腓力四世": "Philip IV of Spain",
  "瑪格麗特·特蕾莎": "Infanta Margaret Theresa",
  "福柯": "Michel Foucault",
  "焦爾達諾": "Luca Giordano",
  "德通布": "Arnoldus des Tombe",
  "崔西·雪佛蘭": "Tracy Chevalier",
  "史嘉莉·祖漢森": "Scarlett Johansson",
  "班克斯": "Banksy",
  "路易十四": "Louis XIV",
  "路易十五": "Louis XV",
  "路易十六": "Louis XVI",
  "德布西": "Claude Debussy",
  "龔古爾兄弟": "the Goncourt brothers",
  "波特萊爾": "Charles Baudelaire",
  "魏爾倫": "Paul Verlaine",
  "蓬巴度夫人": "Madame de Pompadour",
  "讓娜–安托瓦妮特·普瓦松": "Jeanne-Antoinette Poisson",
  "伏爾泰": "Voltaire",
  "維特爾斯巴赫家族": "the Wittelsbach family",
  "科勒": "Charles Collé",
  "多揚": "Gabriel-François Doyen",
  "法爾科內": "Étienne Maurice Falconet",
  "華萊士家族": "the Wallace family",
  "修尼巴爾": "Yinka Shonibare",
  "莎士比亞": "William Shakespeare",
  "彌爾頓": "John Milton",
  "安娜·蘭多爾特": "Anna Landolt",
  "佛洛伊德": "Sigmund Freud",
  "瑪麗·雪萊": "Mary Shelley",
  "威廉·布萊克": "William Blake",
  "布萊克": "William Blake",
  "李維": "Livy",
  "格羅": "Antoine-Jean Gros",
  "傑拉德": "François Gérard",
  "馬拉": "Jean-Paul Marat",
  "夏洛特·科黛": "Charlotte Corday",
  "科黛": "Charlotte Corday",
  "羅伯斯庇爾": "Maximilien Robespierre",
  "卡洛斯四世": "Charles IV of Spain",
  "德拉羅什": "Paul Delaroche",
  "漢尼拔": "Hannibal",
  "查理曼": "Charlemagne",
  "凱欣德·威利": "Kehinde Wiley",
  "腓特烈·威廉三世": "Frederick William III",
  "卡洛琳·繆拉": "Caroline Murat",
  "繆拉家族": "the Murat family",
  "帕米賈尼諾": "Parmigianino",
  "游擊隊女孩": "Guerrilla Girls",
  "馬蒂斯": "Henri Matisse",
  "約瑟夫": "Joseph Bonaparte",
  "斐迪南七世": "Ferdinand VII",
  "伯克": "Edmund Burke",
  "康德": "Immanuel Kant",
  "尼采": "Friedrich Nietzsche",
  "叔本華": "Arthur Schopenhauer",
  "羅斯科": "Mark Rothko",
  "德舒馬雷": "Hugues Duroy de Chaumareys",
  "但丁": "Dante Alighieri",
  "烏戈利諾伯爵": "Count Ugolino",
  "培根": "Francis Bacon",
  "威利·洛特": "Willy Lott",
  "拜倫": "Lord Byron",
  "查理十世": "Charles X",
  "路易–菲臘": "Louis Philippe I",
  "雨果": "Victor Hugo",
  "伽弗洛什": "Gavroche",
  "酷玩樂團": "Coldplay",
  "納爾遜": "Horatio Nelson",
  "占士邦": "James Bond",
  "布魯內爾": "Isambard Kingdom Brunel",
  "薩克雷": "William Makepeace Thackeray",
  "畢沙羅": "Camille Pissarro",
  "安妮·華達": "Agnès Varda",
  "肖夏爾": "Alfred Chauchard",
  "雷蒙迪": "Marcantonio Raimondi",
  "維多琳·默朗": "Victorine Meurent",
  "洛爾": "Laure",
  "安娜·麥克尼爾·惠斯勒": "Anna McNeill Whistler",
  "納達爾": "Nadar",
  "勒魯瓦": "Louis Leroy",
  "卡寧": "Kanin",
  "弗拉基米爾大公": "Grand Duke Vladimir Alexandrovich",
  "拉爾卡": "Larka",
  "杜斯妥也夫斯基": "Fyodor Dostoevsky",
  "儒勒·佩羅": "Jules Perrot",
  "福爾": "Jean-Baptiste Faure",
  "卡蜜兒": "Camille Doncieux",
  "蘇珊": "Suzanne Hoschedé",
  "布蘭奇·奧施德": "Blanche Hoschedé",
  "梅隆夫婦": "Paul and Bunny Mellon",
  "埃斯特爾": "Estelle",
  "奧斯曼男爵": "Baron Haussmann",
  "奧斯曼": "Baron Haussmann",
  "艾琳·沙里戈": "Aline Charigot",
  "菲利普斯": "Duncan Phillips",
  "巴特利特": "Frederic Clay Bartlett",
  "謝弗勒爾": "Michel Eugène Chevreul",
  "桑德海姆": "Stephen Sondheim",
  "西涅克": "Paul Signac",
  "西奧": "Theo van Gogh",
  "博赫": "Eugène Boch",
  "米列": "Paul-Eugène Milliet",
  "貝爾納": "Émile Bernard",
  "柯爾莫哥洛夫": "Andrey Kolmogorov",
  "唐·麥克林": "Don McLean",
  "布拉克": "Georges Braque",
  "波洛克": "Jackson Pollock",
  "艾米莉·弗洛格": "Emilie Flöge",
  "加布里埃爾·明特": "Gabriele Münter",
  "杜斯伯格": "Theo van Doesburg",
  "伊夫·聖羅蘭": "Yves Saint Laurent",
  "菲利波·利比": "Filippo Lippi",
  "韋羅基奧": "Andrea del Verrocchio",
  "好人菲臘": "Philip the Good",
  "伊拉斯謨": "Erasmus",
  "奧拉齊奧·真蒂萊斯基": "Orazio Gentileschi",
  "查理一世": "Charles I of England",
  "托雷–比爾熱": "Théophile Thoré-Bürger",
  "狄德羅": "Denis Diderot",
  "雷諾茲": "Joshua Reynolds",
  "羅斯金": "John Ruskin",
  "布丹": "Eugène Boudin",
  "格萊爾": "Charles Gleyre",
  "西斯萊": "Alfred Sisley",
  "左拉": "Émile Zola",
  "弗萊": "Roger Fry",
  "克拉克森": "Thomas Clarkson",
  "馬克·吐溫": "Mark Twain",
  "愛麗絲·胡珀": "Alice Hooper",
  "克萊斯特": "Heinrich von Kleist",

  // ── 作品（書籍、電影、樂曲及本站未收錄的畫作） ──
  "《歲時記》": "Fasti",
  "《達文西密碼》": "The Da Vinci Code",
  "《焦孔達》": "La Gioconda",
  "《聖禮之爭》": "The Disputation of the Holy Sacrament",
  "《蒂邁歐篇》": "Timaeus",
  "《倫理學》": "Nicomachean Ethics",
  "《創世記》": "Genesis",
  "《外星人》": "E.T. the Extra-Terrestrial",
  "《飛向太空》": "Solaris",
  "《鏡子》": "Mirror",
  "《馬太福音》": "Gospel of Matthew",
  "《舊約》": "Old Testament",
  "《朱迪斯傳》": "Book of Judith",
  "《詞與物》": "The Order of Things",
  "〈快樂島〉": "L'Isle joyeuse",
  "《遊樂畫集》": "Fêtes galantes",
  "《百科全書》": "Encyclopédie",
  "《鞦韆的快樂機會》": "The Happy Accidents of the Swing",
  "《魔髮奇緣》": "Tangled",
  "《科學怪人》": "Frankenstein",
  "《網球場宣誓》": "The Tennis Court Oath",
  "《人民之友》": "L'Ami du peuple",
  "《聖殤》": "Pietà",
  "《大衛》": "David",
  "《基督下葬》": "The Entombment of Christ",
  "《土耳其浴室》": "The Turkish Bath",
  "《戰爭的災難》": "The Disasters of War",
  "《處決馬克西米利安皇帝》": "The Execution of Emperor Maximilian",
  "《格爾尼卡》": "Guernica",
  "《朝鮮大屠殺》": "Massacre in Korea",
  "《神曲》": "The Divine Comedy",
  "《海難場景》": "Scene of Shipwreck",
  "《風景：正午》": "Landscape: Noon",
  "《無畏號》": "The Fighting Temeraire",
  "《薩達那帕拉》": "Sardanapalus",
  "《悲慘世界》": "Les Misérables",
  "《007：空降危機》": "Skyfall",
  "《雨、蒸氣和速度——大西部鐵路》": "Rain, Steam and Speed – The Great Western Railway",
  "《拾穗者》": "The Gleaners and I",
  "《帕里斯的審判》": "The Judgement of Paris",
  "《田園音樂會》": "The Pastoral Concert",
  "《灰與黑的編曲一號》": "Arrangement in Grey and Black No. 1",
  "《黑獅碼頭》": "Black Lion Wharf",
  "《戇豆先生》": "Bean",
  "《伏爾加船夫曲》": "Song of the Volga Boatmen",
  "《散步，莫內夫人與兒子》": "The Walk, Madame Monet and Her Son",
  "《艾蜜莉的異想世界》": "Amélie",
  "《星期天與喬治在公園》": "Sunday in the Park with George",
  "《翹課天才》": "Ferris Bueller's Day Off",
  "《隆河上的星夜》": "Starry Night Over the Rhône",
  "《畫向日葵的梵高》": "The Painter of Sunflowers",
  "《情謎梵高》": "Loving Vincent",
  "《驚聲尖叫》": "Scream",
  "《論藝術的精神》": "Concerning the Spiritual in Art",
  "《風格》": "De Stijl",
  "《乾草堆》": "Haystacks",
  "《帝國的歷程》": "The Course of Empire",
  "《人生的旅程》": "The Voyage of Life",
  "《希望的謬誤》": "Fallacies of Hope",
};
